### ISSUE TITLE
Search addresses by xpub

### ISSUE THREAD

**Issue by xhipster** [byteball/obyte-explorer#15]
Can be very useful feature for those who seeks transparency

**Comment by tarmo888** [comment]
Extended Public keys can have unlimited number of addresses, each address is derived from a public key of each derived path.

So, searching by public key of each address is meaningless because you could just search the address and searching by Extended Public key nearly impossible because there could be unlimited address for that extended public key.

I made a script that let's you generate as many addresses for the wallet from Extended Public Key. I hope it helps https://runkit.com/tarmo888/5d72cf0c75a29c001ae4382f

You can find a xpub for each of your wallet when you click on Gear icon -> Advanced -> Wallet Information.
